#!/usr/bin/env bash
# Re-vendor the editing skills from their upstream repos into .claude/skills/.
#   video-use   (MIT)        https://github.com/browser-use/video-use
#   hyperframes (Apache-2.0) https://github.com/heygen-com/hyperframes
# Usage: scripts/sync-skills.sh            # pulls latest main of both
# Local edits inside .claude/skills/<vendored>/ are overwritten — put project
# customizations in CLAUDE.md or tools/ instead.
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
SKILLS="$ROOT/.claude/skills"
TMP="$(mktemp -d)"
trap 'rm -rf "$TMP"' EXIT

# Published hyperframes skills we use (cut → captions → motion graphics).
HF_SKILLS=(
  hyperframes hyperframes-core hyperframes-cli hyperframes-animation
  hyperframes-keyframes hyperframes-creative hyperframes-registry
  hyperframes-audio media-use embedded-captions talking-head-recut
  motion-graphics general-video
)
# Repo-internal hyperframes doctrine skills worth having for overlays.
HF_INTERNAL=(captions-overlay motion-doctrine cut-the-curve seam-craft)

git clone --depth 1 -q https://github.com/browser-use/video-use "$TMP/video-use"
git clone --depth 1 -q https://github.com/heygen-com/hyperframes "$TMP/hyperframes"

mkdir -p "$SKILLS"

# video-use: SKILL.md + helpers/ must stay siblings.
rm -rf "$SKILLS/video-use"
mkdir -p "$SKILLS/video-use"
cp -R "$TMP/video-use/"{SKILL.md,install.md,helpers,skills,pyproject.toml,LICENSE,README.md} "$SKILLS/video-use/"

for s in "${HF_SKILLS[@]}"; do
  rm -rf "$SKILLS/$s"
  cp -R "$TMP/hyperframes/skills/$s" "$SKILLS/$s"
done
for s in "${HF_INTERNAL[@]}"; do
  rm -rf "$SKILLS/$s"
  cp -R "$TMP/hyperframes/.claude/skills/$s" "$SKILLS/$s"
done
cp "$TMP/hyperframes/LICENSE" "$SKILLS/HYPERFRAMES-LICENSE"

{
  echo "# Vendored skills"
  echo
  echo "Generated by scripts/sync-skills.sh on $(date -u +%Y-%m-%d). Do not hand-edit vendored dirs."
  echo
  echo "| Source | Commit | License | Skills |"
  echo "|---|---|---|---|"
  echo "| browser-use/video-use | $(git -C "$TMP/video-use" rev-parse --short HEAD) | MIT | video-use (+ vendored manim-video under video-use/skills/) |"
  echo "| heygen-com/hyperframes | $(git -C "$TMP/hyperframes" rev-parse --short HEAD) | Apache-2.0 | ${HF_SKILLS[*]} ${HF_INTERNAL[*]} |"
} > "$SKILLS/VENDORED.md"

echo "synced skills into $SKILLS"
